### ISSUE TITLE
is this work for android app project ?

### ISSUE THREAD

**Issue by kishangohel** [pubnub/kotlin#2]

**Comment by Chesteer89** [comment]
Yes, it works for android applications. 

Take a look at some code samples:
https://www.pubnub.com/docs/kotlin-java/pubnub-java-sdk

Feel free to ask any questions, I'll try to help you.

**Comment by kishangohel** [comment]
Actually it's working as listener not working

**Comment by Chesteer89** [comment]
Can you provide more informations?

**Comment by Chesteer89** [comment]
Outdated. Please contact us if you need more help.
