### ISSUE TITLE
Crash after internet is disconnected [v5.0.2]

### ISSUE THREAD

**Issue by buinguyen** [pubnub/kotlin#3]
Hi develop team,

My app had a crash after the internet is disconnected.
I used pubnub-kotlin v5.0.2.
Please check this log to get more detail.
Hope to help you to solve this issue!

`java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:404)
        at java.util.Timer.schedule(Timer.java:200)
        at com.pubnub.api.managers.ReconnectionManager.registerHeartbeatTimer(ReconnectionManager.kt:60)`

**Comment by Chesteer89** [comment]
Thanks for reporting this @buinguyen.

We're working on it and will let you know when the fix is ​​ready.

**Comment by iasif-experlabs** [comment]
I am still getting this exact same issue. Is it still not resolved yet?

**Comment by kleewho** [comment]
@iasif-experlabs Which version are you using?

**Comment by Chesteer89** [comment]
It was fixed in 5.1.0. What's your version?
